# fly.toml app configuration file generated for discord-defender on 2026-07-03T00:49:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-defender'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
